local _, pml = ...

pml.L = pml.L or {}

local L = pml.L

function pml:GetLocalizedString(key)
  return L[key] or key
end

-- enUS default locale
L["ADDON_NAME"] = "Pet Masters League Logs"
L["SETTINGS_TITLE"] = "Settings"
L["LOADED"] = "Loaded - saved logs:"
L["OPEN_WITH"] = "open with: "
L["MAX_LOGS"] = "max number of saved logs reached, the oldest log will be deleted before a new log will be saved.|r"
L["NO_PVP_BATTLE"] = "not a PvP battle! Skipping log.|r"
L["BATTLE_STARTED"] = "battle started at:|r"
L["BATTLE_ENDED"] = "battle ended at:|r"
L["BATTLE_SAVED"] = "battle saved.|r Total saved logs:"
L["OLDEST_REMOVED"] = "oldest battle removed!|r"
L["BREED_INIT_ERROR"] = "ERROR:|r BasePetStats not initialized."
L["UNKNOWN"] = "Unknown"
L["MINIMAP_TOOLTIP1"] = "Pet Masters League Logs|r"
L["MINIMAP_TOOLTIP2"] = "Toggle the addon"
L["DELETE_CONFIRM"] = "Are you sure you want to delete all battle logs and pet usage data?"
L["YES"] = "Yes"
L["NO"] = "No"
L["DATA_DELETED"] = "All pet battle logs and pet usage data have been deleted.|r"
L["SELECT_ALL_BUTTON"] = "Select All"
L["LOGS_BUTTON"] = "Battle Logs"
L["USAGE_BUTTON"] = "Pet Usage"
L["DELETE_BUTTON"] = "Delete Logs"
L["SETTINGS_BUTTON"] = "Settings"
L["MINIMAP_BUTTON"] = "Show minimap button"
L["RESET_BUTTON"] = "Reset Settings"
L["LOCK_FRAME"] = "Lock the addon frame"
L["LOGS_FONT_SIZE"] = "Logs Font Size"
L["FONT_SIZE"] = "Logs Font Size: "
L["BG_OPACITY"] = "Background Opacity"
L["BACKGROUND_OPACITY"] = "Background Opacity: "
L["TEXT_DURATION"] = "Selected Text Duration"
L["TEXT_DURATION1"] = "Selected Text Duration: "
L["TEXT_DURATION2"] = " sec"
L["ADDON_THEME"] = "Addon Theme"
L["LOGS_SELECTED"] = "Battle Logs text selected! Press Ctrl+C to copy."
L["USAGE_SELECTED"] = "Pet Usage text selected! Press Ctrl+C to copy."


if GetLocale() == "deDE" then
  L["ADDON_NAME"] = "Pet Masters League Logs"
  L["SETTINGS_TITLE"] = "Einstellungen"
  L["LOADED"] = "Geladen – gespeicherte Logs:"
  L["OPEN_WITH"] = "Öffnen mit: "
  L["MAX_LOGS"] =
  "Maximale Anzahl gespeicherter Logs erreicht; das älteste Log wird gelöscht, bevor ein neues gespeichert wird.|r"
  L["NO_PVP_BATTLE"] = "Kein PvP-Kampf! Log wird übersprungen.|r"
  L["BATTLE_STARTED"] = "Kampf begonnen um:|r"
  L["BATTLE_ENDED"] = "Kampf beendet um:|r"
  L["BATTLE_SAVED"] = "Kampf gespeichert.|r Gesamtzahl gespeicherter Logs:"
  L["OLDEST_REMOVED"] = "Ältester Kampf entfernt!|r"
  L["BREED_INIT_ERROR"] = "FEHLER:|r BasePetStats nicht initialisiert."
  L["UNKNOWN"] = "Unbekannt"
  L["MINIMAP_TOOLTIP1"] = "Pet Masters League Logs|r"
  L["MINIMAP_TOOLTIP2"] = "Addon umschalten"
  L["DELETE_CONFIRM"] = "Bist du sicher, dass du alle Kampf-Logs und Daten zur Haustiernutzung löschen möchtest?"
  L["YES"] = "Ja"
  L["NO"] = "Nein"
  L["DATA_DELETED"] = "Alle Haustierkampf-Logs und Nutzungsdaten wurden gelöscht.|r"
  L["SELECT_ALL_BUTTON"] = "Alles auswählen"
  L["LOGS_BUTTON"] = "Kampf-Logs"
  L["USAGE_BUTTON"] = "Haustiernutzung"
  L["DELETE_BUTTON"] = "Logs löschen"
  L["SETTINGS_BUTTON"] = "Einstellungen"
  L["MINIMAP_BUTTON"] = "Minikarten-Button anzeigen"
  L["RESET_BUTTON"] = "Einstellungen zurücksetzen"
  L["LOCK_FRAME"] = "Addon-Fenster fixieren"
  L["LOGS_FONT_SIZE"] = "Schriftgröße der Logs"
  L["FONT_SIZE"] = "Schriftgröße der Logs: "
  L["BG_OPACITY"] = "Hintergrund-Deckkraft"
  L["BACKGROUND_OPACITY"] = "Hintergrund-Deckkraft: "
  L["TEXT_DURATION"] = "Dauer des ausgewählten Textes"
  L["TEXT_DURATION1"] = "Anzeigedauer des Texts: "
  L["TEXT_DURATION2"] = " Sek."
  L["ADDON_THEME"] = "Addon-Design"
  L["LOGS_SELECTED"] = "Text der Kampf-Logs ausgewählt! Drücke Strg+C zum Kopieren."
  L["USAGE_SELECTED"] = "Text zur Haustiernutzung ausgewählt! Drücke Strg+C zum Kopieren."
end

if GetLocale() == "esES" then
  L["ADDON_NAME"] = "Pet Masters League Logs"
  L["SETTINGS_TITLE"] = "Configuración"
  L["LOADED"] = "Cargado - registros guardados:"
  L["OPEN_WITH"] = "abrir con: "
  L["MAX_LOGS"] =
  "se ha alcanzado el número máximo de registros guardados; el registro más antiguo se eliminará antes de guardar uno nuevo.|r"
  L["NO_PVP_BATTLE"] = "¡no es una batalla JcJ! Omitiendo registro.|r"
  L["BATTLE_STARTED"] = "batalla iniciada a las:|r"
  L["BATTLE_ENDED"] = "batalla finalizada a las:|r"
  L["BATTLE_SAVED"] = "batalla guardada.|r Total de registros guardados:"
  L["OLDEST_REMOVED"] = "¡se ha eliminado la batalla más antigua!|r"
  L["BREED_INIT_ERROR"] = "ERROR:|r BasePetStats no inicializado."
  L["UNKNOWN"] = "Desconocido"
  L["MINIMAP_TOOLTIP1"] = "Registros de Pet Masters League|r"
  L["MINIMAP_TOOLTIP2"] = "Alternar el addon"
  L["DELETE_CONFIRM"] =
  "¿Estás seguro de que quieres eliminar todos los registros de batalla y los datos de uso de mascotas?"
  L["YES"] = "Sí"
  L["NO"] = "No"
  L["DATA_DELETED"] = "Se han eliminado todos los registros de combates de mascotas y los datos de uso de mascotas.|r"
  L["SELECT_ALL_BUTTON"] = "Seleccionar todo"
  L["LOGS_BUTTON"] = "Registros de combate"
  L["USAGE_BUTTON"] = "Uso de mascotas"
  L["DELETE_BUTTON"] = "Eliminar registros"
  L["SETTINGS_BUTTON"] = "Configuración"
  L["MINIMAP_BUTTON"] = "Mostrar botón del minimapa"
  L["RESET_BUTTON"] = "Restablecer configuración"
  L["LOCK_FRAME"] = "Bloquear marco del addon"
  L["LOGS_FONT_SIZE"] = "Tamaño de fuente de los registros"
  L["FONT_SIZE"] = "Tamaño de fuente de los registros: "
  L["BG_OPACITY"] = "Opacidad del fondo"
  L["BACKGROUND_OPACITY"] = "Opacidad del fondo: "
  L["TEXT_DURATION"] = "Duración del texto seleccionado"
  L["TEXT_DURATION1"] = "Duración del texto seleccionado: "
  L["TEXT_DURATION2"] = " seg"
  L["ADDON_THEME"] = "Tema del addon"
  L["LOGS_SELECTED"] = "¡Texto de registros de combate seleccionado! Pulsa Ctrl+C para copiar."
  L["USAGE_SELECTED"] = "¡Texto de uso de mascotas seleccionado! Pulsa Ctrl+C para copiar."
end

if GetLocale() == "esMX" then
  L["ADDON_NAME"] = "Pet Masters League Logs"
  L["SETTINGS_TITLE"] = "Configuración"
  L["LOADED"] = "Cargado - registros guardados:"
  L["OPEN_WITH"] = "abrir con: "
  L["MAX_LOGS"] =
  "se alcanzó el número máximo de registros guardados, el registro más antiguo será eliminado antes de guardar uno nuevo.|r"
  L["NO_PVP_BATTLE"] = "¡no es una batalla JcJ! Omitiendo registro.|r"
  L["BATTLE_STARTED"] = "batalla iniciada a las:|r"
  L["BATTLE_ENDED"] = "batalla finalizada a las:|r"
  L["BATTLE_SAVED"] = "batalla guardada.|r Total de registros guardados:"
  L["OLDEST_REMOVED"] = "¡batalla más antigua eliminada!|r"
  L["BREED_INIT_ERROR"] = "ERROR:|r BasePetStats no inicializado."
  L["UNKNOWN"] = "Desconocido"
  L["MINIMAP_TOOLTIP1"] = "Registros de la Liga de Maestros de Mascotas|r"
  L["MINIMAP_TOOLTIP2"] = "Mostrar/ocultar el addon"
  L["DELETE_CONFIRM"] = "¿Estás seguro de que deseas eliminar todos los registros de batalla y datos de uso de mascotas?"
  L["YES"] = "Sí"
  L["NO"] = "No"
  L["DATA_DELETED"] = "Todos los registros de batalla de mascotas y datos de uso de mascotas han sido eliminados.|r"
  L["SELECT_ALL_BUTTON"] = "Seleccionar todo"
  L["LOGS_BUTTON"] = "Registros de batalla"
  L["USAGE_BUTTON"] = "Uso de mascotas"
  L["DELETE_BUTTON"] = "Eliminar registros"
  L["SETTINGS_BUTTON"] = "Configuración"
  L["MINIMAP_BUTTON"] = "Mostrar botón en el minimapa"
  L["RESET_BUTTON"] = "Restablecer configuración"
  L["LOCK_FRAME"] = "Bloquear el marco del addon"
  L["LOGS_FONT_SIZE"] = "Tamaño de fuente de los registros"
  L["FONT_SIZE"] = "Tamaño de fuente de registros: "
  L["BG_OPACITY"] = "Opacidad del fondo"
  L["BACKGROUND_OPACITY"] = "Opacidad del fondo: "
  L["TEXT_DURATION"] = "Duración del texto seleccionado"
  L["TEXT_DURATION1"] = "Duración del texto seleccionado: "
  L["TEXT_DURATION2"] = " seg"
  L["ADDON_THEME"] = "Tema del addon"
  L["LOGS_SELECTED"] = "¡Texto de registros de batalla seleccionado! Presiona Ctrl+C para copiar."
  L["USAGE_SELECTED"] = "Texto de uso de mascotas"
end

if GetLocale() == "frFR" then
  L["ADDON_NAME"] = "Pet Masters League Logs"
  L["SETTINGS_TITLE"] = "Paramètres"
  L["LOADED"] = "Chargé - journaux enregistrés :"
  L["OPEN_WITH"] = "ouvrir avec : "
  L["MAX_LOGS"] =
  "nombre maximal de journaux enregistrés atteint ; le plus ancien sera supprimé avant l'enregistrement d'un nouveau.|r"
  L["NO_PVP_BATTLE"] = "pas un combat JcJ ! Journal ignoré.|r"
  L["BATTLE_STARTED"] = "combat commencé à :|r"
  L["BATTLE_ENDED"] = "combat terminé à :|r"
  L["BATTLE_SAVED"] = "combat enregistré.|r Total des journaux enregistrés :"
  L["OLDEST_REMOVED"] = "le plus ancien combat a été supprimé !|r"
  L["BREED_INIT_ERROR"] = "ERREUR :|r BasePetStats non initialisé."
  L["UNKNOWN"] = "Inconnu"
  L["MINIMAP_TOOLTIP1"] = "Pet Masters League Logs|r"
  L["MINIMAP_TOOLTIP2"] = "Activer/Désactiver l'addon"
  L["DELETE_CONFIRM"] =
  "Êtes-vous sûr de vouloir supprimer tous les journaux de combat et les données d'utilisation des mascottes ?"
  L["YES"] = "Oui"
  L["NO"] = "Non"
  L["DATA_DELETED"] = "Tous les journaux de combats de mascottes et les données d'utilisation ont été supprimés.|r"
  L["SELECT_ALL_BUTTON"] = "Tout sélectionner"
  L["LOGS_BUTTON"] = "Journaux"
  L["USAGE_BUTTON"] = "Utilisation"
  L["DELETE_BUTTON"] = "Supprimer"
  L["SETTINGS_BUTTON"] = "Paramètres"
  L["MINIMAP_BUTTON"] = "Afficher le bouton de la minicarte"
  L["RESET_BUTTON"] = "Réinitialiser les paramètres"
  L["LOCK_FRAME"] = "Verrouiller la fenêtre de l'addon"
  L["LOGS_FONT_SIZE"] = "Taille de police des journaux"
  L["FONT_SIZE"] = "Taille de police des journaux : "
  L["BG_OPACITY"] = "Opacité de l'arrière-plan"
  L["BACKGROUND_OPACITY"] = "Opacité de l'arrière-plan : "
  L["TEXT_DURATION"] = "Durée du texte sélectionné"
  L["TEXT_DURATION1"] = "Durée d'affichage du texte sélectionné : "
  L["TEXT_DURATION2"] = " s"
  L["ADDON_THEME"] = "Thème de l'addon"
  L["LOGS_SELECTED"] = "Texte des journaux de combat sélectionné ! Appuyez sur Ctrl+C pour copier."
  L["USAGE_SELECTED"] = "Texte d'utilisation des mascottes sélectionné ! Appuyez sur Ctrl+C pour copier."
end

if GetLocale() == "itIT" then
  L["ADDON_NAME"] = "Pet Masters League Logs"
  L["SETTINGS_TITLE"] = "Impostazioni"
  L["LOADED"] = "Caricato - log salvati:"
  L["OPEN_WITH"] = "apri con: "
  L["MAX_LOGS"] =
  "raggiunto il numero massimo di log salvati; il log più vecchio verrà eliminato prima di salvarne uno nuovo.|r"
  L["NO_PVP_BATTLE"] = "non è una battaglia PvP! Log ignorato.|r"
  L["BATTLE_STARTED"] = "battaglia iniziata alle:|r"
  L["BATTLE_ENDED"] = "battaglia terminata alle:|r"
  L["BATTLE_SAVED"] = "battaglia salvata.|r Totale log salvati:"
  L["OLDEST_REMOVED"] = "battaglia più vecchia rimossa!|r"
  L["BREED_INIT_ERROR"] = "ERRORE:|r BasePetStats non inizializzato."
  L["UNKNOWN"] = "Sconosciuto"
  L["MINIMAP_TOOLTIP1"] = "Pet Masters League Logs|r"
  L["MINIMAP_TOOLTIP2"] = "Attiva/Disattiva l'addon"
  L["DELETE_CONFIRM"] =
  "Sei sicuro di voler eliminare tutti i log delle battaglie e i dati sull'utilizzo degli animali da compagnia?"
  L["YES"] = "Sì"
  L["NO"] = "No"
  L["DATA_DELETED"] = "Tutti i log delle sfide tra mascotte e i dati di utilizzo delle mascotte sono stati eliminati.|r"
  L["SELECT_ALL_BUTTON"] = "Seleziona tutto"
  L["LOGS_BUTTON"] = "Log delle sfide"
  L["USAGE_BUTTON"] = "Utilizzo mascotte"
  L["DELETE_BUTTON"] = "Elimina log"
  L["SETTINGS_BUTTON"] = "Impostazioni"
  L["MINIMAP_BUTTON"] = "Mostra pulsante sulla minimappa"
  L["RESET_BUTTON"] = "Ripristina impostazioni"
  L["LOCK_FRAME"] = "Blocca la finestra dell'addon"
  L["LOGS_FONT_SIZE"] = "Dimensione carattere dei log"
  L["FONT_SIZE"] = "Dimensione carattere log: "
  L["BG_OPACITY"] = "Opacità dello sfondo"
  L["BACKGROUND_OPACITY"] = "Opacità sfondo: "
  L["TEXT_DURATION"] = "Durata del testo selezionato"
  L["TEXT_DURATION1"] = "Durata selezione testo: "
  L["TEXT_DURATION2"] = " sec"
  L["ADDON_THEME"] = "Tema dell'addon"
  L["LOGS_SELECTED"] = "Testo dei log delle sfide selezionato! Premi Ctrl+C per copiare."
  L["USAGE_SELECTED"] = "Testo dell'utilizzo mascotte selezionato! Premi Ctrl+C per copiare."
end

if GetLocale() == "koKR" then
  L["ADDON_NAME"] = "Pet Masters League Logs"
  L["SETTINGS_TITLE"] = "설정"
  L["LOADED"] = "로드됨 - 저장된 기록:"
  L["OPEN_WITH"] = "열기 도구: "
  L["MAX_LOGS"] = "저장된 기록이 최대치에 도달했습니다. 새 기록을 저장하기 전에 가장 오래된 기록이 삭제됩니다.|r"
  L["NO_PVP_BATTLE"] = "PvP 전투가 아닙니다! 기록을 건너뜁니다.|r"
  L["BATTLE_STARTED"] = "전투 시작 시간:|r"
  L["BATTLE_ENDED"] = "전투 종료 시간:|r"
  L["BATTLE_SAVED"] = "전투가 저장되었습니다.|r 총 저장된 기록:"
  L["OLDEST_REMOVED"] = "가장 오래된 전투 기록이 삭제되었습니다!|r"
  L["BREED_INIT_ERROR"] = "오류:|r BasePetStats가 초기화되지 않았습니다."
  L["UNKNOWN"] = "알 수 없음"
  L["MINIMAP_TOOLTIP1"] = "Pet Masters League Logs|r"
  L["MINIMAP_TOOLTIP2"] = "애드온 켜기/끄기"
  L["DELETE_CONFIRM"] = "모든 전투 기록과 애완동물 사용 데이터를 삭제하시겠습니까?"
  L["YES"] = "예"
  L["NO"] = "아니요"
  L["DATA_DELETED"] = "모든 애완동물 대전 기록 및 사용 데이터가 삭제되었습니다.|r"
  L["SELECT_ALL_BUTTON"] = "모두 선택"
  L["LOGS_BUTTON"] = "대전 기록"
  L["USAGE_BUTTON"] = "애완동물 사용 현황"
  L["DELETE_BUTTON"] = "기록 삭제"
  L["SETTINGS_BUTTON"] = "설정"
  L["MINIMAP_BUTTON"] = "미니맵 버튼 표시"
  L["RESET_BUTTON"] = "설정 초기화"
  L["LOCK_FRAME"] = "애드온 창 잠금"
  L["LOGS_FONT_SIZE"] = "로그 글꼴 크기"
  L["FONT_SIZE"] = "기록 글꼴 크기: "
  L["BG_OPACITY"] = "배경 불투명도"
  L["BACKGROUND_OPACITY"] = "배경 불투명도: "
  L["TEXT_DURATION"] = "선택된 텍스트 지속 시간"
  L["TEXT_DURATION1"] = "텍스트 표시 시간: "
  L["TEXT_DURATION2"] = "초"
  L["ADDON_THEME"] = "애드온 테마"
  L["LOGS_SELECTED"] = "대전 기록 텍스트가 선택되었습니다! Ctrl+C를 눌러 복사하세요."
  L["USAGE_SELECTED"] = "애완동물 사용 현황 텍스트가 선택되었습니다! Ctrl+C를 눌러 복사하세요."
end

if GetLocale() == "ptBR" then
  L["ADDON_NAME"] = "Pet Masters League Logs"
  L["SETTINGS_TITLE"] = "Configurações"
  L["LOADED"] = "Carregado - registros salvos:"
  L["OPEN_WITH"] = "abrir com: "
  L["MAX_LOGS"] =
  "número máximo de registros salvos atingido; o registro mais antigo será excluído antes que um novo seja salvo.|r"
  L["NO_PVP_BATTLE"] = "não é uma batalha PvP! Ignorando registro.|r"
  L["BATTLE_STARTED"] = "batalha iniciada em:|r"
  L["BATTLE_ENDED"] = "batalha encerrada em:|r"
  L["BATTLE_SAVED"] = "batalha salva.|r Total de registros salvos:"
  L["OLDEST_REMOVED"] = "batalha mais antiga removida!|r"
  L["BREED_INIT_ERROR"] = "ERRO:|r BasePetStats não inicializado."
  L["UNKNOWN"] = "Desconhecido"
  L["MINIMAP_TOOLTIP1"] = "Pet Masters League Logs|r"
  L["MINIMAP_TOOLTIP2"] = "Alternar o addon"
  L["DELETE_CONFIRM"] = "Tem certeza de que deseja excluir todos os registros de batalha e dados de uso de mascotes?"
  L["YES"] = "Sim"
  L["NO"] = "Não"
  L["DATA_DELETED"] = "Todos os registros de batalha de mascotes e dados de uso de mascotes foram excluídos.|r"
  L["SELECT_ALL_BUTTON"] = "Selecionar Tudo"
  L["LOGS_BUTTON"] = "Registros de Batalha"
  L["USAGE_BUTTON"] = "Uso de Mascotes"
  L["DELETE_BUTTON"] = "Excluir Registros"
  L["SETTINGS_BUTTON"] = "Configurações"
  L["MINIMAP_BUTTON"] = "Mostrar botão no minimapa"
  L["RESET_BUTTON"] = "Redefinir Configurações"
  L["LOCK_FRAME"] = "Bloquear a janela do addon"
  L["LOGS_FONT_SIZE"] = "Tamanho da Fonte dos Logs"
  L["FONT_SIZE"] = "Tamanho da Fonte dos Registros: "
  L["BG_OPACITY"] = "Opacidade do Fundo"
  L["BACKGROUND_OPACITY"] = "Opacidade do Fundo: "
  L["TEXT_DURATION"] = "Duração do Texto Selecionado"
  L["TEXT_DURATION1"] = "Duração do Texto Selecionado: "
  L["TEXT_DURATION2"] = " seg"
  L["ADDON_THEME"] = "Tema do Addon"
  L["LOGS_SELECTED"] = "Texto dos Registros de Batalha selecionado! Pressione Ctrl+C para copiar."
  L["USAGE_SELECTED"] = "Texto de Uso de Mascotes selecionado! Pressione Ctrl+C para copiar."
end

if GetLocale() == "ruRU" then
  L["ADDON_NAME"] = "Pet Masters League Logs"
  L["SETTINGS_TITLE"] = "Настройки"
  L["LOADED"] = "Загружено — сохраненных логов:"
  L["OPEN_WITH"] = "открыть с помощью: "
  L["MAX_LOGS"] = "достигнут лимит сохраненных логов; самый старый лог будет удален перед сохранением нового.|r"
  L["NO_PVP_BATTLE"] = "это не PvP-бой! Лог пропускается.|r"
  L["BATTLE_STARTED"] = "бой начался в:|r"
  L["BATTLE_ENDED"] = "бой завершился в:|r"
  L["BATTLE_SAVED"] = "бой сохранен.|r Всего логов:"
  L["OLDEST_REMOVED"] = "самый старый бой удален!|r"
  L["BREED_INIT_ERROR"] = "ОШИБКА:|r BasePetStats не инициализированы."
  L["UNKNOWN"] = "Неизвестно"
  L["MINIMAP_TOOLTIP1"] = "Pet Masters League Logs|r"
  L["MINIMAP_TOOLTIP2"] = "Переключить состояние аддона"
  L["DELETE_CONFIRM"] = "Вы уверены, что хотите удалить все логи боев и данные об использовании питомцев?"
  L["YES"] = "Да"
  L["NO"] = "Нет"
  L["DATA_DELETED"] = "Все журналы битв питомцев и данные об их использовании удалены.|r"
  L["SELECT_ALL_BUTTON"] = "Выбрать всё"
  L["LOGS_BUTTON"] = "Журналы битв"
  L["USAGE_BUTTON"] = "Использование питомцев"
  L["DELETE_BUTTON"] = "Удалить журналы"
  L["SETTINGS_BUTTON"] = "Настройки"
  L["MINIMAP_BUTTON"] = "Показывать кнопку у мини-карты"
  L["RESET_BUTTON"] = "Сбросить настройки"
  L["LOCK_FRAME"] = "Закрепить окно аддона"
  L["LOGS_FONT_SIZE"] = "Размер шрифта логов"
  L["FONT_SIZE"] = "Размер шрифта журнала: "
  L["BG_OPACITY"] = "Прозрачность фона"
  L["BACKGROUND_OPACITY"] = "Прозрачность фона: "
  L["TEXT_DURATION"] = "Длительность отображения текста"
  L["TEXT_DURATION1"] = "Длительность выделения текста: "
  L["TEXT_DURATION2"] = " сек."
  L["ADDON_THEME"] = "Тема оформления"
  L["LOGS_SELECTED"] = "Текст журнала битв выделен! Нажмите Ctrl+C для копирования."
  L["USAGE_SELECTED"] = "Текст использования питомцев выделен! Нажмите Ctrl+C для копирования."
end

if GetLocale() == "zhCN" then
  L["ADDON_NAME"] = "宠物大师联盟战斗记录"
  L["SETTINGS_TITLE"] = "设置"
  L["LOADED"] = "已加载 - 已保存记录："
  L["OPEN_WITH"] = "打开方式："
  L["MAX_LOGS"] = "已达到最大记录数量，保存新记录前将删除最旧的记录。|r"
  L["NO_PVP_BATTLE"] = "非 PvP 战斗！跳过记录。|r"
  L["BATTLE_STARTED"] = "战斗开始于：|r"
  L["BATTLE_ENDED"] = "战斗结束于：|r"
  L["BATTLE_SAVED"] = "战斗已保存。|r 总计已保存记录："
  L["OLDEST_REMOVED"] = "已移除最旧的战斗记录！|r"
  L["BREED_INIT_ERROR"] = "错误：|r BasePetStats 未初始化。"
  L["UNKNOWN"] = "未知"
  L["MINIMAP_TOOLTIP1"] = "宠物大师联盟战斗记录|r"
  L["MINIMAP_TOOLTIP2"] = "切换插件显示"
  L["DELETE_CONFIRM"] = "确定要删除所有战斗记录和宠物使用数据吗？"
  L["YES"] = "是"
  L["NO"] = "否"
  L["DATA_DELETED"] = "所有宠物对战记录和宠物使用数据均已删除。|r"
  L["SELECT_ALL_BUTTON"] = "全选"
  L["LOGS_BUTTON"] = "对战记录"
  L["USAGE_BUTTON"] = "宠物使用情况"
  L["DELETE_BUTTON"] = "删除记录"
  L["SETTINGS_BUTTON"] = "设置"
  L["MINIMAP_BUTTON"] = "显示小地图按钮"
  L["RESET_BUTTON"] = "重置设置"
  L["LOCK_FRAME"] = "锁定插件窗口"
  L["LOGS_FONT_SIZE"] = "日志字体大小"
  L["FONT_SIZE"] = "记录字体大小: "
  L["BG_OPACITY"] = "背景不透明度"
  L["BACKGROUND_OPACITY"] = "背景不透明度: "
  L["TEXT_DURATION"] = "选中文字持续时间"
  L["TEXT_DURATION1"] = "选中文字持续时间: "
  L["TEXT_DURATION2"] = " 秒"
  L["ADDON_THEME"] = "插件主题"
  L["LOGS_SELECTED"] = "已选中对战记录文本！按 Ctrl+C 复制。"
  L["USAGE_SELECTED"] = "已选中宠物使用情况文本！按 Ctrl+C 复制。"
end

if GetLocale() == "zhTW" then
  L["ADDON_NAME"] = "寵物大師聯盟日誌"
  L["SETTINGS_TITLE"] = "設定"
  L["LOADED"] = "已載入 - 已儲存的日誌："
  L["OPEN_WITH"] = "開啟方式："
  L["MAX_LOGS"] = "已達到最大保存日誌數量，最舊的日誌將被刪除，然後才會儲存新的日誌。|r"
  L["NO_PVP_BATTLE"] = "非 PvP 對戰！跳過日誌。|r"
  L["BATTLE_STARTED"] = "戰鬥開始時間：|r"
  L["BATTLE_ENDED"] = "戰鬥結束時間：|r"
  L["BATTLE_SAVED"] = "戰鬥已儲存。|r 已儲存日誌總數："
  L["OLDEST_REMOVED"] = "最舊的戰鬥日誌已移除！|r"
  L["BREED_INIT_ERROR"] = "錯誤：|r BasePetStats 未初始化。"
  L["UNKNOWN"] = "未知"
  L["MINIMAP_TOOLTIP1"] = "寵物大師聯賽日誌|r"
  L["MINIMAP_TOOLTIP2"] = "切換插件"
  L["DELETE_CONFIRM"] = "您確定要刪除所有戰鬥日誌和寵物使用資料嗎？"
  L["YES"] = "是"
  L["NO"] = "否"
  L["DATA_DELETED"] = "所有寵物對戰記錄和寵物使用資料已被刪除。|r"
  L["SELECT_ALL_BUTTON"] = "全選"
  L["LOGS_BUTTON"] = "對戰紀錄"
  L["USAGE_BUTTON"] = "寵物使用情況"
  L["DELETE_BUTTON"] = "刪除記錄"
  L["SETTINGS_BUTTON"] = "設定"
  L["MINIMAP_BUTTON"] = "顯示小地圖按鈕"
  L["RESET_BUTTON"] = "重設設定"
  L["LOCK_FRAME"] = "鎖定插件框架"
  L["LOGS_FONT_SIZE"] = "日誌字體大小"
  L["FONT_SIZE"] = "記錄字體大小："
  L["BG_OPACITY"] = "背景不透明度"
  L["BACKGROUND_OPACITY"] = "背景不透明度："
  L["TEXT_DURATION"] = "選定文字持續時間"
  L["TEXT_DURATION1"] = "所選文字持續時間："
  L["TEXT_DURATION2"] = "秒"
  L["ADDON_THEME"] = "外掛程式主題"
  L["LOGS_SELECTED"] = "戰鬥日誌文字已選取！按 Ctrl+C 複製。"
  L["USAGE_SELECTED"] = "寵物使用文字已選取！按 Ctrl+C 複製。"
end
